maint: generate ChangeLog from git commit messages
* ChangeLog: Remove, as it is not maintained manually any longer.
* Makefile.am (gen-ChangeLog): Add phony target to create the ChangeLog
file in the distribution tarball from the git commit messages - starting
from 2014 - and concatenating the file 'ChangeLog-2013'.
(dist-hook): Add the above new target as dependency.
* ChangeLog-2013: Add a newline at the top for nicer separation in
the concatenated ChangeLog file in the distribution tarball.
Bump Copyright year.
* import-gnulib.config (maintainer_modules): Add 'gitlog-to-changelog'
module.  Furthermore create an empty ChangeLog file to silence automake,
and set DO_NOT_WANT_CHANGELOG_DRIVER environment variable as we do not
want the import to fail if the changelog driver is not installed.
* build-aux/git-log-fix: Add rules to fix some git commit messages
during ChangeLog generation.
* build-aux/.gitignore: Add entry for 'gitlog-to-changelog'.
* build-aux/.cvsignore: Likewise.
* .gitignore: Likewise.
* README-hacking: Remove item to add a ChangeLog entry, and instead
mention to give a decent commit message.  In the command sequence for
a complete session, remove ChangeLog editing, too.
* doc/find-maint.texi (Release Information): Remove ChangeLog editing.
*

Signed-off-by: James Youngman <jay@gnu.org>

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -25,8 +25,30 @@ tool-versions.txt: Makefile
 	makeinfo --version ) > $@
 
 
-dist-hook: findutils-check-pofiles findutils-check-testfiles
+dist-hook: gen-ChangeLog findutils-check-pofiles findutils-check-testfiles
 
+# gen-Changelog must still work when $(top_srcdir)/.git does not exist
+# because "make distcheck" verifies that you can "make dist" from the
+# tarball generated by "make dist".  We still need that to work.
+.PHONY: gen-ChangeLog
+gen-ChangeLog:
+	$(AM_V_GEN)if test -d $(top_srcdir)/.git; then             \
+	  gen_start_date='2014-01-01' ;                            \
+	  log_fix="$(top_srcdir)/build-aux/git-log-fix" ;          \
+	  test -e "$$log_fix"                                      \
+	    && amend_git_log="--amend=$$log_fix"                   \
+	    || amend_git_log=;                                     \
+	  { $(top_srcdir)/build-aux/gitlog-to-changelog            \
+	      --srcdir=$(top_srcdir)                               \
+	      $$amend_git_log --since=$$gen_start_date             \
+	      && cat $(top_srcdir)/ChangeLog-2013 ;                \
+	    } > $(distdir)/cl-t                                    \
+	      && { rm -f $(distdir)/ChangeLog                      \
+	             && mv $(distdir)/cl-t $(distdir)/ChangeLog; } \
+	else                                                       \
+	  echo "WARNING: $@: cannot generate ChangeLog since" >&2 && \
+	  echo "$(top_srcdir) has no .git subdirectory" >&2 ;      \
+	fi
 
 ## Check that we actually shipped all the .po files.  If this rule fails,
 ## check ALL_LINGUAS in configure.in against the po files in the source
